jobs:
  include:
    - name: "Website"
      language: node_js
      node_js: '12.13'
      cache:
        directories:
          - ~/.npm
          - ~/.cache
      install:
        - npm install
      script:
        - npm run test:cov
      after_script:
        - npx codecov@3
