import { TechStackIcon } from '../interfaces/TechStackIcon';

type iconsOptions = {
  [key: string]: TechStackIcon;
};

export const techStackIcons: iconsOptions = {
  angular: { src: 'angular', name: 'Angular' },
  apollo: { src: 'apollo', name: 'Apollo Client' },
  archlinux: { src: 'archlinux', name: 'Arch Linux' },
  babel: { src: 'babel', name: 'Babel' },
  codecov: { src: 'codecov', name: 'Codecov' },
  cookie: { src: 'cookie', name: 'Cookies' },
  css: { src: 'css', name: 'CSS3' },
  cypress: { src: 'cypress', name: 'Cypress' },
  django: { src: 'django', name: 'Django' },
  datagrip: { src: 'datagrip', name: 'Datagrip' },
  docker: { src: 'docker', name: 'Docker' },
  emotion: { src: 'emotion', name: 'Emotion' },
  es6: { src: 'es6', name: 'ES6' },
  express: { src: 'express', name: 'Express' },
  firebase: { src: 'firebase', name: 'Firebase' },
  github: { src: 'github', name: 'Github' },
  graphql: { src: 'graphql', name: 'GraphQL' },
  hibernate: { src: 'hibernate', name: 'Hibernate' },
  html: { src: 'html', name: 'HTML5' },
  intellij: { src: 'intellij-idea', name: 'Intellij Idea' },
  java: { src: 'java', name: 'Java' },
  javascript: { src: 'javascript', name: 'Javascript' },
  jest: { src: 'jest', name: 'Jest' },
  mariadb: { src: 'mariadb', name: 'MariaDB' },
  'material-ui': { src: 'material-ui', name: 'Material UI' },
  mongodb: { src: 'mongodb', name: 'MongoDB' },
  mssql: { src: 'mssql', name: 'MsSQL' },
  mysql: { src: 'mysql', name: 'MySQL' },
  nestjs: { src: 'nestjs', name: 'NestJS' },
  nextjs: { src: 'nextjs', name: 'Next.js' },
  nodejs: { src: 'nodejs', name: 'Node.js' },
  npm: { src: 'npm', name: 'Node Packet Manager' },
  nuxt: { src: 'nuxt', name: 'Nuxt.js' },
  postgresql: { src: 'postgresql', name: 'PostgreSQL' },
  prettier: { src: 'prettier', name: 'Prettier' },
  pycharm: { src: 'pycharm', name: 'Pycharm' },
  python: { src: 'python', name: 'Python' },
  r: { src: 'r', name: 'R' },
  react: { src: 'react', name: 'React' },
  reactivex: { src: 'reactivex', name: 'Rxjs' },
  'react-router': { src: 'react-router', name: 'React Router' },
  'react-testing-library': {
    src: 'react-testing-library',
    name: 'React Testing Library',
  },
  redux: { src: 'redux', name: 'Redux' },
  'redux-saga': { src: 'redux-saga', name: 'Redux Saga' },
  rest: { src: 'rest', name: 'REST' },
  sass: { src: 'sass', name: 'Sass/Scss' },
  sequelize: { src: 'sequelize', name: 'Sequelize' },
  spring: { src: 'spring', name: 'Spring' },
  'styled-components': { src: 'styled-components', name: 'Styled Components' },
  'travis-ci': { src: 'travis-ci', name: 'Travis CI' },
  typescript: { src: 'typescript', name: 'Typescript' },
  ubuntu: { src: 'ubuntu', name: 'Ubuntu' },
  'visual-studio-code': {
    src: 'visual-studio-code',
    name: 'Visual Studio Code',
  },
  vue: { src: 'vue', name: 'Vue' },
  webpack: { src: 'webpack', name: 'Webpack' },
  websockets: { src: 'websocket', name: 'Websockets' },
  webstorm: { src: 'webstorm', name: 'Webstorm' },
  windows: { src: 'windows', name: 'Windows' },
};
